[versions]
aniyomi-mpv-lib = "1.17.n"
arthenica-smartexceptions = "0.2.1"
constraint-layout = "1.1.1"
ffmpeg-kit = "1.17"
media = "1.7.0"
seeker = "1.2.2"
truetypeparser = "2.1.4"
nanohttpd-version = "2.3.1"

[libraries]
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd-version" }
aniyomi-mpv = { module = "com.github.aniyomiorg:aniyomi-mpv-lib", version.ref = "aniyomi-mpv-lib" }
arthenica-smartexceptions = { module = "com.arthenica:smart-exception-java", version.ref = "arthenica-smartexceptions" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraint-layout" }
ffmpeg-kit = { module = "com.github.jmir1:ffmpeg-kit", version.ref = "ffmpeg-kit" }
mediasession = { module = "androidx.media:media", version.ref = "media" }
seeker = { module = "io.github.2307vivek:seeker", version.ref = "seeker" }
truetypeparser = { module = "io.github.yubyf:truetypeparser-light", version.ref = "truetypeparser" }

torrentserver = "com.github.Diegopyl1209:torrentserver-aniyomi:c18f58e51b"
media-router = "androidx.mediarouter:mediarouter:1.7.0"
cast-play-services = "com.google.android.gms:play-services-cast-framework:22.1.0"

[bundles]
cast = ["media-router", "cast-play-services"]
