blank_issues_enabled: false
contact_links:
  - name: ğŸ§‘â€ğŸ’» Discord
    url: https://discord.gg/8eQBJuWAY
    about: Common questions are answered here
  - name: âŒ Help with Extensions
    url: https://github.com/salmanbappi/Anikku-Mod/discussions
    about: For extension-related questions/issues
  - name: ğŸ–¥ï¸ AniZen GitHub
    url: https://github.com/salmanbappi/Anikku-Mod
    about: Source code, releases, and documentation
